Generate centroids with polylabel
anandthakker/us-atlas pull request #32
Opened 2016-09-25 23:05 UTC by dereklieu

Applies `mapbox/polylabel` to find centroids.

Since `polylabel` doesn't handle `MultiPolygon` types, I first try to combine them using `turf.union`. If the combined feature is still a multipolygon, I just use `turf.centroid`.

2016-09-26 10:31 UTC, anandthakker commented on Makefile
> +		--named-layer=states:geojson/albers/centroid-states.geojson \
let's name these `state-centroids`, `county-centroids`, `district-centroids` (or something like it) -- the reason being, if we make sure that there are no layer-name collisions, we can use Mapbox's vector-tile "compositing", where they combine VTs from different tilesets on the server side if you use a url like `mapbox://devseed.tileset-one,devseed.tileset-two`.

2016-09-26 10:34 UTC, anandthakker commented on centroids
> +        center = turf.centroid(combined).geometry.coordinates
I worry that the actual centroid of a MultiPolygon will often fall outside of the shape.  Instead, could we use `turf-area` on each of the MultiPolygon's constituent polygon parts, reconstruct the largest one into a `Polygon` feature, and apply polylabel to that?

2016-09-26 10:35 UTC, anandthakker commented on Makefile
> +geojson/albers/centroid-%: geojson/albers/%
Might be faster to use the simplified files `geojson/albers/us-10m/%` for input.

2016-09-26 10:35 UTC, anandthakker requested changes
Looks good!  Couple suggestions.

2016-09-26 13:30 UTC, dereklieu commented on Makefile
> +		--named-layer=states:geojson/albers/centroid-states.geojson \
Ah didn't know about that, but that makes sense.

2016-09-26 13:47 UTC, dereklieu commented on Makefile
> +		--named-layer=states:geojson/albers/centroid-states.geojson \
Gonna go with `states-centroids`, `counties-centroids`, `districts-centroids` since the other layers are plural too.

2016-09-26 13:48 UTC, anandthakker commented on Makefile
> +		--named-layer=states:geojson/albers/centroid-states.geojson \
👍

2016-09-26 23:57 UTC, dereklieu commented on Makefile
> +geojson/albers/centroid-%: geojson/albers/%
@anandthakker I tried this, but polylabel choked on what appears to be a very simplified polygon that only had three points. Bumping it back up to the non-simplified geometries.

2016-09-26 23:59 UTC, dereklieu commented
@anandthakker ok, trying out your idea of using `polylabel` on the largest `polygon` in a `multipolygon` feature. Code is pushed, will update `mapbox://washingtonpost.ds-2016-election-centroids` when it finishes.

2016-09-27 11:44 UTC, anandthakker approved these changes

2016-09-27 14:06 UTC, merged